version: '3.9'
services:
  api:
    container_name: nestjs-boilerplate-api
    build:
      context: ''
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=host.docker.internal
    restart: unless-stopped
    ports:
      - 3333:3333
    networks:
      - nestjs-boilerplate-api
networks:
  nestjs-boilerplate-api:
    driver: bridge
